### ISSUE TITLE
Standalone App?

### ISSUE THREAD

**Issue by Brice187** [patrik7/django-email-retargeting#1]
Hey Patrik,

is it possible to use this App as standalone tool? I setup up an LXC Container for a mail scheduling purpose and try to get django-email-retargeting up and running. Could you please be more specific in your quick start guide? Or maybe you answer to this issue and i will add a pull request with a detailed how to :)

**Comment by patrik7** [comment]
Hi Brice,

I have put more details into README. Can you sahre more details about what kind of emails do you want to send, to see if this is a good fit for your.

To run as a standalone app is very easy, just follow typical django tutorial steps. but don't include "polls" but use this package. You can create and manage the emails thru the django admin interface.

How do you want to trigger email sends?

**Comment by Brice187** [comment]
Hi Patrik,

i want to build something like this https://github.com/beezee/Bumper-deprecated in python.

A typical example is to send a mail to a recipient and bcc 14days@my-mail-server.org to get the message after 14 days back in my inbox.

You know what i mean?

**Comment by patrik7** [comment]
This plugin/app does not react to received emails, to schedule an email, you need to execute python code. So wyou would need to implement that part.

this may be offbase, but have you thought of using the Boomerang plugin for gmail? https://www.boomeranggmail.com/

**Comment by Brice187** [comment]
i know that Django-email-retargeting is not the OOTB solution i need, but may be a good starting point. May be i will code something in the next few weeks to check, if this project fits my needs.

Btw: I don't use gmail and i will not send (possible) sensitive information to a third party service. ;)

**Comment by patrik7** [comment]
Got it! Okay, I am happy to merge anything that adds value :)
